# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - winp2000groupa

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://winp2000acr.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_36579920d4dd4320b2e495b4b2277ef6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c6d621704754472fbcb0e6b4c8a75775 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: winp2000acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_36579920d4dd4320b2e495b4b2277ef6 }}/go-app/go-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'winp2000groupa'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1bcc04e851b446759c0d7e69c2aa0aa9 }}
        images: 'winp2000acr.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_36579920d4dd4320b2e495b4b2277ef6 }}/go-app/go-app:${{ github.sha }}'